# Generated by Django 4.1.7 on 2023-04-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaTres', '0002_alumnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='fecha_nacimiento',
        ),
    ]
