# Generated by Django 4.1.7 on 2023-04-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaTres', '0003_remove_alumnos_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=40)),
                ('apellido', models.TextField(max_length=40)),
                ('edad', models.DecimalField(decimal_places=0, max_digits=5)),
                ('nacimiento', models.DateField()),
            ],
        ),
    ]
