# Generated by Django 4.1.7 on 2023-04-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaTres', '0004_profesores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=40)),
                ('categoria', models.TextField(max_length=100)),
                ('detalles', models.TextField(max_length=100)),
                ('fecha_finalizacion', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
