# Generated by Django 4.1.7 on 2023-04-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaTres', '0006_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('Categoria', models.CharField(max_length=80)),
                ('Descripccion_Posteo', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profesores',
        ),
        migrations.DeleteModel(
            name='Tareas',
        ),
    ]
