# Generated by Django 4.1.7 on 2023-04-19 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EntregaTres', '0008_publicacion_delete_posteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='publisher',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='Categoria',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='Descripccion_Posteo',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='Titulo',
            field=models.TextField(max_length=30),
        ),
    ]
