# Generated by Django 4.1.7 on 2023-04-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaTres', '0009_persona_publicacion_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='publisher',
        ),
    ]
