# Generated by Django 4.1.7 on 2023-04-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaTres', '0011_publicacion_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Publicaciones'),
        ),
    ]
