# Generated by Django 4.1.7 on 2023-04-22 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaTres', '0013_perfil_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='Creado_El',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='Imagen',
            field=models.ImageField(upload_to='Perfil'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='Imagen',
            field=models.ImageField(upload_to='Publicaciones'),
        ),
    ]
