# Generated by Django 4.1.7 on 2023-04-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaTres', '0016_publicacion_categorias_alter_publicacion_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='Categoria',
            new_name='Topico',
        ),
    ]
