# Generated by Django 4.1.7 on 2023-04-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaTres', '0017_rename_categoria_publicacion_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='edad',
            field=models.IntegerField(default=1, max_length=99),
            preserve_default=False,
        ),
    ]
