# Generated by Django 4.1.7 on 2023-04-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaTres', '0018_perfil_apellido_perfil_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
